#!C:\xampp74\php\php.exe
<?php

if (php_sapi_name() !== 'cli')
{
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use MiniCli\CommandCall;

$app = new App();
$app->setSignature("minicli hello name [ user=name ]");

$app->registerCommand('help', function(CommandCall $call) use ($app) {
    $app->printSignature();
    print_r($call->params);
});

$app->runCommand($argv);